config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  resources :rooms
  resources :reservations

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :room
end

app/models/room.rb
class Room < ActiveRecord::Base
  has_many :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @rooms = Room.all
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def new
    @reservation = Reservation.new
    @reservation.room_id = params[:room_id]
  end

  def create
    @reservation = Reservation.new
    @reservation.start_at = Date.new(params[:reservation]['start_at(1i)'].to_i)

    if @reservation.update(reservation_params)
      redirect_to @reservation.room
    else
      render :new
    end

  end

  private

  def reservation_params
    params.require(:reservation).permit(:email, :room_id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def show
    @room = Room.find params[:id]
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GtfoApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
select room

<% @rooms.each do |room| %>
  <p><%= link_to room.name, new_reservation_path(room_id: room.id) %></p>
<% end %>  

app/views/reservations/new.html.erb
<%= form_for @reservation do |f| %>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :start_at, 'Time' %>
    <%= f.time_select :start_at, :default => {:hour => '2', :minute => '00'} %>
  </p>

  <p>
    <%= f.text_field :room_id %>
  </p>

  <button>Reserve!</button>
<% end %>

app/views/rooms/show.html.erb
<%= @room.name %>

<% @room.reservations.each do |r| %>
  <p><%= r.start_at %> <%= r.email %></p>
<% end %>